apiVersion: v1
kind: Service
metadata:
  name: devsecops-app
  labels:
    app: devsecops-app
spec:
  type: ClusterIP
  selector:
    app: devsecops-app
  ports:
  - port: 80
    targetPort: 5000
    name: http